package com.ningyuan.wx.model;

import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Jan 21 14:46:12 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_location" )
public class WxLocationModel extends BaseModel {

    @Column(name = "open_id" )
    private String openId;

    /**
     * 维度
     */
    @Column(name = "lat" )
    private String lat;

    /**
     * 经度
     */
    @Column(name = "lng" )
    private String lng;

    /**
     * 国家
     */
    @Column(name = "nation" )
    private String nation;

    /**
     * 省
     */
    @Column(name = "province" )
    private String province;

    /**
     * 市
     */
    @Column(name = "city" )
    private String city;

    /**
     * 区
     */
    @Column(name = "district" )
    private String district;

    /**
     * 街道
     */
    @Column(name = "street" )
    private String street;

    /**
     * 门牌
     */
    @Column(name = "street_number" )
    private String streetNumber;

    @Column(name = "create_time" )
    private Date createTime;

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getLat() {
        return this.lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getLng() {
        return this.lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getNation() {
        return this.nation;
    }

    public void setNation(String nation) {
        this.nation = nation;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public String getStreetNumber() {
        return this.streetNumber;
    }

    public void setStreetNumber(String streetNumber) {
        this.streetNumber = streetNumber;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
