package com.ningyuan.wx.model;

import javax.persistence.Column;
import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed May 15 10:20:22 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_msg_result" )
public class WxMsgResultModel extends BaseModel {

    @Column(name = "open_id" )
    private String openId;

    @Column(name = "promote_type" )
    private String promoteType;

    /**
     * 类型, 用于区分一个模块下的多种消息
     */
    @FiledComment(text = "类型, 用于区分一个模块下的多种消息" )
    @Column(name = "type" )
    private String type;

    @Column(name = "template_id" )
    private String templateId;

    @Column(name = "page" )
    private String page;

    @Column(name = "form_id" )
    private String formId;

    @Column(name = "emphasis_keyword" )
    private String emphasisKeyword;

    /**
     * 模板变量值
     */
    @FiledComment(text = "模板变量值" )
    @Column(name = "data" )
    private String data;

    /**
     * 接口响应_错误码
     */
    @FiledComment(text = "接口响应_错误码" )
    @Column(name = "err_code" )
    private Long errCode;

    /**
     * 接口响应_错误信息
     */
    @FiledComment(text = "接口响应_错误信息" )
    @Column(name = "err_msg" )
    private String errMsg;

    @Column(name = "success_time" )
    private Date successTime;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getPromoteType() {
        return this.promoteType;
    }

    public void setPromoteType(String promoteType) {
        this.promoteType = promoteType;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTemplateId() {
        return this.templateId;
    }

    public void setTemplateId(String templateId) {
        this.templateId = templateId;
    }

    public String getPage() {
        return this.page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    public String getFormId() {
        return this.formId;
    }

    public void setFormId(String formId) {
        this.formId = formId;
    }

    public String getEmphasisKeyword() {
        return this.emphasisKeyword;
    }

    public void setEmphasisKeyword(String emphasisKeyword) {
        this.emphasisKeyword = emphasisKeyword;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public Long getErrCode() {
        return this.errCode;
    }

    public void setErrCode(Long errCode) {
        this.errCode = errCode;
    }

    public String getErrMsg() {
        return this.errMsg;
    }

    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

    public Date getSuccessTime() {
        return this.successTime;
    }

    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
