package com.ningyuan.wx.model;

import com.ningyuan.base.BaseModel;
import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Nov 22 11:14:32 CST 2018.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_notify_info" )
public class WxNotifyInfoModel extends BaseModel {

    @Column(name = "appoint_id" )
    private String appointId;

    @Column(name = "open_id" )
    private String openId;

    @Column(name = "time_end" )
    private String timeEnd;

    @Column(name = "transaction_id" )
    private String transactionId;

    public String getAppointId() {
        return this.appointId;
    }

    public void setAppointId(String appointId) {
        this.appointId = appointId;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getTimeEnd() {
        return this.timeEnd;
    }

    public void setTimeEnd(String timeEnd) {
        this.timeEnd = timeEnd;
    }

    public String getTransactionId() {
        return this.transactionId;
    }

    public void setTransactionId(String transactionId) {
        this.transactionId = transactionId;
    }

}
