package com.ningyuan.wx.model;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed May 15 08:51:08 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_pay2user_result" )
public class WxPay2userResultModel extends BaseModel {

    @Column(name = "promote_type" )
    private String promoteType;

    @Column(name = "open_id" )
    private String openId;

    /**
     * 原因,通常为相关用户open_id
     */
    @FiledComment(text = "原因,通常为相关用户open_id" )
    @Column(name = "reason" )
    private String reason;

    @Column(name = "mch_appid" )
    private String mchAppid;

    /**
     * 商户订单号
     */
    @FiledComment(text = "商户订单号" )
    @Column(name = "partner_trade_no" )
    private String partnerTradeNo;

    @Column(name = "amount" )
    private String amount;

    /**
     * 企业付款备注
     */
    @FiledComment(text = "企业付款备注" )
    @Column(name = "res_desc" )
    private String resDesc;

    @Column(name = "result_code" )
    private String resultCode;

    @Column(name = "err_code" )
    private String errCode;

    /**
     * 接口调用结果json
     */
    @FiledComment(text = "接口调用结果json" )
    @Column(name = "result_text" )
    private String resultText;

    @Column(name = "success_time" )
    private Date successTime;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getPromoteType() {
        return this.promoteType;
    }

    public void setPromoteType(String promoteType) {
        this.promoteType = promoteType;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getMchAppid() {
        return this.mchAppid;
    }

    public void setMchAppid(String mchAppid) {
        this.mchAppid = mchAppid;
    }

    public String getPartnerTradeNo() {
        return this.partnerTradeNo;
    }

    public void setPartnerTradeNo(String partnerTradeNo) {
        this.partnerTradeNo = partnerTradeNo;
    }

    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getResDesc() {
        return this.resDesc;
    }

    public void setResDesc(String resDesc) {
        this.resDesc = resDesc;
    }

    public String getResultCode() {
        return this.resultCode;
    }

    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    public String getErrCode() {
        return this.errCode;
    }

    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    public String getResultText() {
        return this.resultText;
    }

    public void setResultText(String resultText) {
        this.resultText = resultText;
    }

    public Date getSuccessTime() {
        return this.successTime;
    }

    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
