package com.ningyuan.wx.model;

import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Feb 14 12:00:07 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_red_pack_result" )
public class WxRedPackResultModel extends BaseModel {

    @Column(name = "promote_type" )
    private String promoteType;

    @Column(name = "open_id" )
    private String openId;

    /**
     * 商户订单号
     */
    @Column(name = "mch_billno" )
    private String mchBillno;

    /**
     * 业务结果
     */
    @Column(name = "result_code" )
    private String resultCode;

    /**
     * 错误代码
     */
    @Column(name = "err_code" )
    private String errCode;

    /**
     * total_amount
     */
    @Column(name = "total_amount" )
    private String totalAmount;

    @Column(name = "success_time" )
    private Date successTime;

    @Column(name = "created_time" )
    private Date createdTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getPromoteType() {
        return this.promoteType;
    }

    public void setPromoteType(String promoteType) {
        this.promoteType = promoteType;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getMchBillno() {
        return this.mchBillno;
    }

    public void setMchBillno(String mchBillno) {
        this.mchBillno = mchBillno;
    }

    public String getResultCode() {
        return this.resultCode;
    }

    public void setResultCode(String resultCode) {
        this.resultCode = resultCode;
    }

    public String getErrCode() {
        return this.errCode;
    }

    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    public String getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(String totalAmount) {
        this.totalAmount = totalAmount;
    }

    public Date getSuccessTime() {
        return this.successTime;
    }

    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
