package com.ningyuan.wx.model;
import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy
 * <p>Date: Fri Apr 03 11:38:15 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_relate" )
public class WxRelateModel extends BaseModel {

    /**
     * 待定
     */
    @FiledComment(text = "待定" )
    @Column(name = "type" )
    private String type;

    @Column(name = "open_id" )
    private String openId;

    /**
     * 分享人的open_id
     */
    @FiledComment(text = "分享人的open_id" )
    @Column(name = "parent_open_id" )
    private String parentOpenId;

    @Column(name = "create_time" )
    private Date createTime;

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getParentOpenId() {
        return this.parentOpenId;
    }

    public void setParentOpenId(String parentOpenId) {
        this.parentOpenId = parentOpenId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

}
