package com.ningyuan.wx.model;

import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Mar 25 17:23:39 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_relate" )
public class WxRelateModel extends BaseModel {

    @Column(name = "promote_type" )
    private String promoteType;

    /**
     * 按活动需求定义分割形式
     */
    @Column(name = "params" )
    private String params;

    @Column(name = "open_id" )
    private String openId;

    public String getPromoteType() {
        return this.promoteType;
    }

    public void setPromoteType(String promoteType) {
        this.promoteType = promoteType;
    }

    public String getParams() {
        return this.params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

}
