package com.ningyuan.wx.model;

import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;
import java.io.InputStream;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Nov 22 11:14:32 CST 2018.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wx_user" )
public class WxUserModel extends BaseModel {

    @Column(name = "subscribe" )
    private String subscribe;

    @Column(name = "open_id" )
    private String openId;

    @Column(name = "unionid" )
    private String unionid;

    @Column(name = "nickname" )
    private InputStream nickname;

    @Column(name = "sex" )
    private Integer sex;

    @Column(name = "language" )
    private String language;

    @Column(name = "city" )
    private String city;

    @Column(name = "province" )
    private String province;

    @Column(name = "country" )
    private String country;

    @Column(name = "headimgurl" )
    private String headimgurl;

    @Column(name = "subscribe_time" )
    private String subscribeTime;

    @Column(name = "remark" )
    private String remark;

    @Column(name = "groupid" )
    private String groupid;

    @Column(name = "user_agent" )
    private String userAgent;

    @Column(name = "promote_type" )
    private String promoteType;

    public String getSubscribe() {
        return this.subscribe;
    }

    public void setSubscribe(String subscribe) {
        this.subscribe = subscribe;
    }

    public String getOpenId() {
        return openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getUnionid() {
        return this.unionid;
    }

    public void setUnionid(String unionid) {
        this.unionid = unionid;
    }

    public InputStream getNickname() {
        return this.nickname;
    }

    public void setNickname(InputStream nickname) {
        this.nickname = nickname;
    }

    public Integer getSex() {
        return this.sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getHeadimgurl() {
        return this.headimgurl;
    }

    public void setHeadimgurl(String headimgurl) {
        this.headimgurl = headimgurl;
    }

    public String getSubscribeTime() {
        return this.subscribeTime;
    }

    public void setSubscribeTime(String subscribeTime) {
        this.subscribeTime = subscribeTime;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getGroupid() {
        return this.groupid;
    }

    public void setGroupid(String groupid) {
        this.groupid = groupid;
    }

    public String getUserAgent() { return userAgent; }

    public void setUserAgent(String userAgent) { this.userAgent = userAgent; }

    public String getPromoteType() { return promoteType; }

    public void setPromoteType(String promoteType) { this.promoteType = promoteType; }
}
