package com.ningyuan.mobile.controller;

import com.ningyuan.base.BaseController;
import com.ningyuan.core.Context;
import com.ningyuan.mobile.dto.UserInfoDto;
import com.ningyuan.mobile.service.IShopCustomerService;
import com.ningyuan.utils.ParamsUtils;
import com.ningyuan.utils.TemplateUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.servlet.ModelAndView;

/**
 * generated by Generate Controller.groovy 
 * <p>Date: Fri Apr 03 11:10:05 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Controller
@RequestMapping("shop/user")
public class ShopCustomerController extends BaseController {

    @Autowired
    private IShopCustomerService shopCustomerService;

    @RequestMapping(value = "index/{openId}",method = RequestMethod.GET)
    @ResponseBody
    public ModelAndView callbackHandle(@PathVariable("openId") String openId){
        return new ModelAndView("redirect:".concat(ParamsUtils.getRomote())
                .concat(TemplateUtils.replaceAll("/app/shop/index.html?openId=${openId}", openId)));
    }

    @RequestMapping(value = "/getInfo",method = RequestMethod.GET)
    @ResponseBody
    public UserInfoDto getUserInfo(){
        String openId = Context.getOpenId();
        return shopCustomerService.queryUserInfo(openId);
    }
}
