package com.ningyuan.mobile.controller;

import com.ningyuan.base.BaseController;
import com.ningyuan.bean.front.Rets;
import com.ningyuan.core.Context;
import com.ningyuan.mobile.dto.CartAddDto;
import com.ningyuan.mobile.dto.ShopCartDto;
import com.ningyuan.mobile.model.ShopCartModel;
import com.ningyuan.mobile.service.IGoodsService;
import com.ningyuan.mobile.service.IShopCartService;
import com.ningyuan.mobile.service.IShopGoodsSkuService;
import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.math.BigDecimal;
import java.util.List;

/**
 * generated by Generate Controller.groovy 
 * <p>Date: Sat Mar 21 14:54:11 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Controller
@RequestMapping("shop/cart")
public class ShopCartController extends BaseController {
    @Autowired
    private IShopCartService cartService;

    @RequestMapping(value = "/queryByUser",method = RequestMethod.GET)
    @ResponseBody
    public Object getByUser(){
        String openId = Context.getOpenId();
        List<ShopCartDto> list = cartService.queryCart(openId);
        return Rets.success(list);
    }

    @RequestMapping(value = "/add",method = RequestMethod.POST)
    @ResponseBody
    public Object add(@RequestBody CartAddDto cartDto){
        String openId = Context.getOpenId();
        cartDto.setOpenId(openId);
        Integer result = cartService.addCartItem(cartDto, openId);
        return Rets.success(result);
    }

    @RequestMapping(value="/count",method = RequestMethod.GET)
    @ResponseBody
    public Object count(){
        String openId = Context.getOpenId();
        ShopCartModel shopCartModel = new ShopCartModel();
        shopCartModel.setOpenId(openId);
        return Rets.success(cartService.selectCount(shopCartModel));
    }

    @RequestMapping(value = "/update/{id}/{count}", method = RequestMethod.POST)
    @ResponseBody
    public Object update(@PathVariable("id") Long id, @PathVariable("count") String count){
        ShopCartModel queryModel = new ShopCartModel();
        queryModel.setId(id);
        ShopCartModel cart = cartService.selectByPrimaryKey(queryModel);
        cart.setCount(new BigDecimal(count));
        cartService.updateByPrimaryKeySelective(cart);
        return Rets.success();
    }

    @RequestMapping(value = "/delete", method = RequestMethod.DELETE)
    @ResponseBody
    public Object remove(@RequestParam Long id){
        String openId = Context.getOpenId();
        ShopCartModel queryModel = new ShopCartModel();
        queryModel.setId(id);
        ShopCartModel cart = cartService.selectByPrimaryKey(queryModel);
        if(StringUtils.equals(cart.getOpenId(), openId)){
            cartService.deleteByPrimaryKey(cart);
        }
        return Rets.success();
    }
}
