package com.ningyuan.mobile.controller;

import com.ningyuan.base.BaseController;
import com.ningyuan.mobile.dto.UserInfoDto;
import com.ningyuan.mobile.service.IShopCustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

/**
 * generated by Generate Controller.groovy 
 * <p>Date: Fri Apr 03 11:10:05 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Controller
@RequestMapping("shop/user")
public class ShopCustomerController extends BaseController {

    @Autowired
    private IShopCustomerService shopCustomerService;

    @RequestMapping(value = "/getInfo/{openId}",method = RequestMethod.GET)
    @ResponseBody
    public UserInfoDto getUserInfo(@PathVariable("openId") String openId){
        UserInfoDto userInfoDto = shopCustomerService.queryUserInfo(openId);
        return userInfoDto;
    }
}
