package com.ningyuan.mobile.controller;

import com.ningyuan.base.BaseController;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.beans.factory.annotation.Autowired;
import com.ningyuan.mobile.service.IShopOrderService;

/**
 * generated by Generate Controller.groovy 
 * <p>Date: Sat Mar 21 14:54:11 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Controller
@RequestMapping("shop/order")
public class ShopOrderController extends BaseController {

    @Autowired
    private IShopOrderService shopOrderService;

}
