package com.ningyuan.wx.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.wx.model.WxLocationModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Mon Jan 21 10:35:35 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxLocationMapper extends Mapper<WxLocationModel> {

}
