package com.ningyuan.wx.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.wx.model.WxMsgResultModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Wed May 15 10:20:29 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxMsgResultMapper extends Mapper<WxMsgResultModel> {

}
