package com.ningyuan.wx.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.wx.model.WxNotifyInfoModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Tue Nov 20 14:30:10 CST 2018.</p>
 *
 * @author (zengrc)
 */

public interface WxNotifyInfoMapper extends Mapper<WxNotifyInfoModel> {

}
