package com.ningyuan.wx.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.wx.model.WxPay2userResultModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Tue May 14 17:51:46 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxPay2userResultMapper extends Mapper<WxPay2userResultModel> {

}
