package com.ningyuan.wx.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.wx.model.WxRelateModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Mon Mar 25 15:39:26 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxRelateMapper extends Mapper<WxRelateModel> {

}
