package com.ningyuan.wx.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.wx.model.WxRedPackResultModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Thu Feb 14 11:29:54 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxRedPackResultMapper extends Mapper<WxRedPackResultModel> {

}
