package com.ningyuan.wx.daomapper.mapper;

import com.ningyuan.wx.model.wxsa.WxsaCustomerModel;
import tk.mybatis.mapper.common.Mapper;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Tue Aug 20 09:48:04 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxsaCustomerMapper extends Mapper<WxsaCustomerModel> {

}
