package com.ningyuan.wx.daomapper.mapper;

import com.ningyuan.wx.model.wxsa.WxsaOutMsgModel;
import tk.mybatis.mapper.common.Mapper;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Mon Aug 12 15:43:51 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxsaOutMsgMapper extends Mapper<WxsaOutMsgModel> {

}
