package com.ningyuan.wx.daomapper.mapper;

import com.ningyuan.wx.model.wxsa.WxsaSubscribeModel;
import tk.mybatis.mapper.common.Mapper;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Mon Oct 07 17:14:16 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface WxsaSubscribeMapper extends Mapper<WxsaSubscribeModel> {

}
