package com.ningyuan.wx.daomapper.mapper;

import com.ningyuan.wx.model.WxUserModel;
import tk.mybatis.mapper.common.Mapper;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Wed Oct 24 09:50:21 CST 2018.</p>
 *
 * @author (zengrc)
 */

public interface WxUserMapper extends Mapper<WxUserModel> {

}
