package com.ningyuan.mobile.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.mobile.model.ShopOrderItemModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Tue Mar 24 19:29:46 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface ShopOrderItemMapper extends Mapper<ShopOrderItemModel> {

}
