package com.ningyuan.mobile.daomapper.mapper;

import com.ningyuan.mobile.dto.ShopCartDto;
import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.mobile.model.ShopCartModel;

import java.util.List;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface ShopCartMapper extends Mapper<ShopCartModel> {
    List<ShopCartDto> queryCart(String openId);
}
