package com.ningyuan.mobile.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.mobile.model.ShopFavoriteModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Tue Mar 24 16:55:30 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface ShopFavoriteMapper extends Mapper<ShopFavoriteModel> {

}
