package com.ningyuan.mobile.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.mobile.model.ShopGoodsSkuModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface ShopGoodsSkuMapper extends Mapper<ShopGoodsSkuModel> {

}
