package com.ningyuan.mobile.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.mobile.model.ShopReceiveRecordModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Fri Apr 03 15:21:29 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface ShopReceiveRecordMapper extends Mapper<ShopReceiveRecordModel> {

}
