package com.ningyuan.mobile.daomapper.mapper;

import com.ningyuan.mobile.dto.OrderDto;
import org.apache.ibatis.annotations.Param;
import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.mobile.model.ShopOrderModel;

import java.util.List;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface ShopOrderMapper extends Mapper<ShopOrderModel> {
    List<OrderDto> getOrders(@Param("openId") String openId, @Param("status") Integer status);
}
