package com.ningyuan.mobile.daomapper.mapper;

import tk.mybatis.mapper.common.Mapper;
import com.ningyuan.mobile.model.ShopCustomerModel;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Fri Apr 03 11:08:59 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface ShopCustomerMapper extends Mapper<ShopCustomerModel> {

}
