package com.ningyuan.mobile.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.mobile.model.ShopFavoriteModel;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue Mar 24 16:55:30 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface IShopFavoriteService extends IBaseService<ShopFavoriteModel> {

}
