package com.ningyuan.mobile.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.mobile.dto.*;
import com.ningyuan.mobile.model.ShopCustomerModel;
import com.ningyuan.mobile.model.ShopOrderModel;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Fri Apr 03 11:08:59 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface IShopCustomerService extends IBaseService<ShopCustomerModel> {

    void updateCustomer(ShopOrderModel orderModel);

    UserInfoDto queryUserInfo(String openId);

    ShopCustomerModel checkuser(String openId);

    // 打开红包
    String openRedpacket(String openId);

    TaskStatusDto getTaskStatus(String openId);

    ParentUserDto getParentOpenId(String openId);

    List<UserDto> getRecommend(String openId);

    List<UserDto> getTeam(String openId);

    List<TaskDto> listTask(String openId);
}
