package com.ningyuan.mobile.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.mobile.dto.CartAddDto;
import com.ningyuan.mobile.dto.ShopCartDto;
import com.ningyuan.mobile.model.ShopCartModel;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface IShopCartService extends IBaseService<ShopCartModel> {

    List<ShopCartDto> queryCart(String openId);

    Integer addCartItem(CartAddDto cartDto, String openId);

    void deleteCartList(List<ShopCartDto> cartList);
}
