package com.ningyuan.mobile.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.mobile.dto.OrderDto;
import com.ningyuan.mobile.model.ShopOrderItemModel;
import com.ningyuan.mobile.model.ShopOrderModel;
import com.ningyuan.wx.service.IWxRelateService;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface IShopOrderService extends IBaseService<ShopOrderModel>, IWxRelateService<ShopOrderModel> {

    void saveOrder(ShopOrderModel order, List<ShopOrderItemModel> itemList);

    void cancelOrder(String orderSn);

    ShopOrderModel confirmReceive(String orderSn);

    List<OrderDto> getOrders(String openId, Integer status);
}
