package com.ningyuan.mobile.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.mobile.model.ShopOrderItemModel;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue Mar 24 19:29:46 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface IShopOrderItemService extends IBaseService<ShopOrderItemModel> {

}
