package com.ningyuan.mobile.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.mobile.dto.RedPacketDto;
import com.ningyuan.mobile.dto.RedPacketRecordDto;
import com.ningyuan.mobile.model.ShopWalletModel;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Fri Apr 03 14:41:01 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface IShopWalletService extends IBaseService<ShopWalletModel> {

    List<RedPacketDto> getCashList(String openId);

    String getCashSum();

    void updateWallet(String openId);

    List<RedPacketRecordDto> getRecordList(String openId);
}
