package com.ningyuan.mobile.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.mobile.model.ShopCustomerModel;
import com.ningyuan.mobile.model.ShopOrderModel;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Fri Apr 03 11:08:59 CST 2020.</p>
 *
 * @author (zengrc)
 */

public interface IShopCustomerService extends IBaseService<ShopCustomerModel> {

    void updateCustomer(ShopOrderModel orderModel);
}
