package com.ningyuan.mobile.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.mobile.daomapper.mapper.ShopAttrKeyMapper;
import com.ningyuan.mobile.model.ShopAttrKey;
import com.ningyuan.mobile.model.ShopAttrVal;
import com.ningyuan.mobile.service.IAttrKeyService;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Service
public class IAttrKeyServiceImpl extends BaseServiceImpl<ShopAttrKeyMapper, ShopAttrKey> implements IAttrKeyService {

    @Override
    public List<ShopAttrVal> getAttrVals() {
        return null;
    }
}
