package com.ningyuan.mobile.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.mobile.daomapper.mapper.ShopOrderItemMapper;
import com.ningyuan.mobile.model.ShopOrderItemModel;
import com.ningyuan.mobile.service.IShopOrderItemService;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue Mar 24 19:29:46 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Service
public class ShopOrderItemServiceImpl extends BaseServiceImpl<ShopOrderItemMapper, ShopOrderItemModel> implements IShopOrderItemService {

}
