package com.ningyuan.mobile.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.mobile.daomapper.mapper.ShopFavoriteMapper;
import com.ningyuan.mobile.model.ShopFavoriteModel;
import com.ningyuan.mobile.service.IShopFavoriteService;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue Mar 24 16:55:30 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Service
public class ShopFavoriteServiceImpl extends BaseServiceImpl<ShopFavoriteMapper, ShopFavoriteModel> implements IShopFavoriteService {

}
