package com.ningyuan.mobile.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.mobile.daomapper.mapper.ShopGoodsSkuMapper;
import com.ningyuan.mobile.model.ShopGoodsSkuModel;
import com.ningyuan.mobile.service.IShopGoodsSkuService;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Service
public class ShopGoodsSkuServiceImpl extends BaseServiceImpl<ShopGoodsSkuMapper, ShopGoodsSkuModel> implements IShopGoodsSkuService {

}
