package com.ningyuan.route.model;


import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Mar 20 16:46:27 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="bg_resource" )
public class BgResourceModel extends BaseModel {

    @Column(name = "resource" )
    private String resource;

    @Column(name = "des" )
    private String des;

    public String getResource() {
        return this.resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }

    public String getDes() {
        return this.des;
    }

    public void setDes(String des) {
        this.des = des;
    }

}
