package com.ningyuan.route.model;

import com.ningyuan.base.BaseModel;
import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Mar 20 16:46:27 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="bg_role" )
public class BgRoleModel extends BaseModel {

    @Column(name = "name" )
    private String name;

    @Column(name = "des" )
    private String des;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDes() {
        return this.des;
    }

    public void setDes(String des) {
        this.des = des;
    }



}
