package com.ningyuan.route.model;

import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Mar 20 16:46:27 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="bg_role_route" )
public class BgRoleRouteModel extends BaseModel {

    @Column(name = "role_id" )
    private Long roleId;

    @Column(name = "route_id" )
    private Long routeId;

    public Long getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public Long getRouteId() {
        return this.routeId;
    }

    public void setRouteId(Long routeId) {
        this.routeId = routeId;
    }

}
