package com.ningyuan.route.model;


import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Apr 08 15:43:53 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="bg_route" )
public class BgRouteModel extends BaseModel {

    /**
     * 是否为目录
     */
    @Column(name = "is_menu" )
    private Boolean isMenu;

    @Column(name = "parent_id" )
    private Long parentId;

    /**
     * 降序，越大越前面
     */
    @Column(name = "seq" )
    private Long seq;

    @Column(name = "name" )
    private String name;

    @Column(name = "state" )
    private String state;

    @Column(name = "ctrl" )
    private String ctrl;

    @Column(name = "url" )
    private String url;

    @Column(name = "view" )
    private String view;

    @Column(name = "resolve" )
    private String resolve;

    public Boolean getIsMenu() {
        return this.isMenu;
    }

    public void setIsMenu(Boolean isMenu) {
        this.isMenu = isMenu;
    }

    public Long getParentId() {
        return this.parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getSeq() {
        return this.seq;
    }

    public void setSeq(Long seq) {
        this.seq = seq;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getCtrl() {
        return this.ctrl;
    }

    public void setCtrl(String ctrl) {
        this.ctrl = ctrl;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getView() {
        return this.view;
    }

    public void setView(String view) {
        this.view = view;
    }

    public String getResolve() {
        return this.resolve;
    }

    public void setResolve(String resolve) {
        this.resolve = resolve;
    }

}
