package com.ningyuan.route.model;

import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Mar 21 12:03:57 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="bg_user" )
public class BgUserModel extends BaseModel {

    @Column(name = "username" )
    private String username;

    @Column(name = "password" )
    private String password;

    @Column(name = "enabled" )
    private Boolean enabled;

    @Column(name = "account_non_expired" )
    private Boolean accountNonExpired;

    @Column(name = "credentials_non_expired" )
    private Boolean credentialsNonExpired;

    @Column(name = "account_non_locked" )
    private Boolean accountNonLocked;

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getEnabled() {
        return this.enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    public Boolean getAccountNonExpired() {
        return this.accountNonExpired;
    }

    public void setAccountNonExpired(Boolean accountNonExpired) {
        this.accountNonExpired = accountNonExpired;
    }

    public Boolean getCredentialsNonExpired() {
        return this.credentialsNonExpired;
    }

    public void setCredentialsNonExpired(Boolean credentialsNonExpired) {
        this.credentialsNonExpired = credentialsNonExpired;
    }

    public Boolean getAccountNonLocked() {
        return this.accountNonLocked;
    }

    public void setAccountNonLocked(Boolean accountNonLocked) {
        this.accountNonLocked = accountNonLocked;
    }

}
