package com.ningyuan.wx.model.wxsa;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Fri Aug 30 16:47:05 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wxsa_out_msg" )
public class WxsaOutMsgModel extends BaseModel {

    /**
     * 接收到的消息事件
     */
    @FiledComment(text = "接收到的消息事件" )
    @Column(name = "in_event_type" )
    private String inEventType;

    /**
     * 接收到的消息类型
     */
    @FiledComment(text = "接收到的消息类型" )
    @Column(name = "in_msg_type" )
    private String inMsgType;

    /**
     * 菜单对应的eventkey
     */
    @FiledComment(text = "菜单对应的eventkey" )
    @Column(name = "in_event_key" )
    private String inEventKey;

    /**
     * 关键词
     */
    @FiledComment(text = "关键词" )
    @Column(name = "key_word" )
    private String keyWord;

    /**
     * 响应消息类型
     */
    @FiledComment(text = "响应消息类型" )
    @Column(name = "out_msg_type" )
    private String outMsgType;

    /**
     * 响应的文本消息内容
     */
    @FiledComment(text = "响应的文本消息内容" )
    @Column(name = "content" )
    private String content;

    /**
     * 素材media_id
     */
    @FiledComment(text = "素材media_id" )
    @Column(name = "media_id" )
    private String mediaId;

    /**
     * 响应的图文消息内容
     */
    @FiledComment(text = "响应的图文消息内容" )
    @Column(name = "articles" )
    private String articles;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getInEventType() {
        return this.inEventType;
    }

    public void setInEventType(String inEventType) {
        this.inEventType = inEventType;
    }

    public String getInMsgType() {
        return this.inMsgType;
    }

    public void setInMsgType(String inMsgType) {
        this.inMsgType = inMsgType;
    }

    public String getInEventKey() {
        return this.inEventKey;
    }

    public void setInEventKey(String inEventKey) {
        this.inEventKey = inEventKey;
    }

    public String getKeyWord() {
        return this.keyWord;
    }

    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    public String getOutMsgType() {
        return this.outMsgType;
    }

    public void setOutMsgType(String outMsgType) {
        this.outMsgType = outMsgType;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getMediaId() {
        return this.mediaId;
    }

    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }

    public String getArticles() {
        return this.articles;
    }

    public void setArticles(String articles) {
        this.articles = articles;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
