package com.ningyuan.wx.model.wxsa;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Oct 09 11:22:22 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wxsa_subscribe" )
public class WxsaSubscribeModel extends BaseModel {

    @Column(name = "open_id" )
    private String openId;

    @Column(name = "scene_id" )
    private String sceneId;

    /**
     * 来源id, t_media表的id
     */
    @FiledComment(text = "来源id, t_media表的id" )
    @Column(name = "source_id" )
    private String sourceId;

    /**
     * 是否已经取消关注
     */
    @FiledComment(text = "是否已经取消关注" )
    @Column(name = "has_unsubscribe" )
    private Boolean hasUnsubscribe;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getSceneId() {
        return this.sceneId;
    }

    public void setSceneId(String sceneId) {
        this.sceneId = sceneId;
    }

    public String getSourceId() {
        return this.sourceId;
    }

    public void setSourceId(String sourceId) {
        this.sourceId = sourceId;
    }

    public Boolean getHasUnsubscribe() {
        return this.hasUnsubscribe;
    }

    public void setHasUnsubscribe(Boolean hasUnsubscribe) {
        this.hasUnsubscribe = hasUnsubscribe;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
