package com.ningyuan.wx.model.wxsa;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Sep 02 10:15:06 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="wxsa_customer" )
public class WxsaCustomerModel extends BaseModel {

    @Column(name = "open_id" )
    private String openId;

    /**
     * 预约id
     */
    @FiledComment(text = "预约id" )
    @Column(name = "appoint_id" )
    private String appointId;

    /**
     * 学员id
     */
    @FiledComment(text = "学员id" )
    @Column(name = "student_id" )
    private String studentId;

    /**
     * 业务员id
     */
    @FiledComment(text = "业务员id" )
    @Column(name = "counterman_id" )
    private String countermanId;

    /**
     * 关注来源
     */
    @FiledComment(text = "关注来源" )
    @Column(name = "parent_open_id" )
    private String parentOpenId;

    /**
     * 关注来源文章
     */
    @FiledComment(text = "关注来源文章" )
    @Column(name = "article_id" )
    private String articleId;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getAppointId() {
        return this.appointId;
    }

    public void setAppointId(String appointId) {
        this.appointId = appointId;
    }

    public String getStudentId() {
        return this.studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getCountermanId() {
        return this.countermanId;
    }

    public void setCountermanId(String countermanId) {
        this.countermanId = countermanId;
    }

    public String getParentOpenId() {
        return this.parentOpenId;
    }

    public void setParentOpenId(String parentOpenId) {
        this.parentOpenId = parentOpenId;
    }

    public String getArticleId() {
        return this.articleId;
    }

    public void setArticleId(String articleId) {
        this.articleId = articleId;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
