package com.ningyuan.route.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.route.model.BgRouteModel;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IBgRouteService extends IBaseService<BgRouteModel> {

    List<BgRouteModel> getRouteByRole(Long roleId);

//    List<BgRouteRoleDto> getRouteByRoleId(Long roleId);
}
