package com.ningyuan.route.service;


import com.ningyuan.base.IBaseService;
import com.ningyuan.route.model.BgResourceModel;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IBgResourceService extends IBaseService<BgResourceModel> {

    List<BgResourceModel> getResourcesByRole(long id);

//    List<BgResourceRouteDto> getResourcesByRoute(long id);

}
