package com.ningyuan.route.service;

import com.ningyuan.route.dto.SettingDto;
import com.ningyuan.route.dto.ShopUserDto;
import com.ningyuan.route.dto.ShopUserQueryDto;

import java.util.List;
import java.util.Map;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IShopUserService {

    List<ShopUserDto> listUser(ShopUserQueryDto queryDto);

    void updateUserByid(ShopUserDto shopUserDto);

    SettingDto getSettingDto();

    void updateSetting(SettingDto settingDto);
}
