package com.ningyuan.route.service;

import com.ningyuan.route.dto.ShopAddressDto;
import com.ningyuan.route.dto.ShopInviterDto;
import com.ningyuan.route.dto.ShopOrderDto;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IShopCustomerService {
    List<ShopInviterDto> getInviteList(String mobile);

    List<ShopAddressDto> getAddressList(String mobile, String defaultAddress);

    List<ShopOrderDto> getOrderList(String orderSn);
}
