package com.ningyuan.mobile.model;

import javax.persistence.Column;
import com.ningyuan.base.annotation.FiledComment;
import javax.persistence.Table;
import com.ningyuan.base.BaseModel;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Mar 18 11:33:46 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="cms_banner" )
public class CmsBannerModel extends BaseModel {

    /**
     * banner图id
     */
    @FiledComment(text = "banner图id" )
    @Column(name = "id_file" )
    private Long idFile;

    /**
     * 界面
     */
    @FiledComment(text = "界面" )
    @Column(name = "page" )
    private String page;

    /**
     * 参数
     */
    @FiledComment(text = "参数" )
    @Column(name = "param" )
    private String param;

    /**
     * 标题
     */
    @FiledComment(text = "标题" )
    @Column(name = "title" )
    private String title;

    /**
     * 类型
     */
    @FiledComment(text = "类型" )
    @Column(name = "type" )
    private String type;

    /**
     * 点击banner跳转到url
     */
    @FiledComment(text = "点击banner跳转到url" )
    @Column(name = "url" )
    private String url;

    public Long getIdFile() {
        return this.idFile;
    }

    public void setIdFile(Long idFile) {
        this.idFile = idFile;
    }

    public String getPage() {
        return this.page;
    }

    public void setPage(String page) {
        this.page = page;
    }

    public String getParam() {
        return this.param;
    }

    public void setParam(String param) {
        this.param = param;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

}
