package com.ningyuan.mobile.model;

import com.ningyuan.base.BaseModel;

import javax.persistence.Column;
import javax.persistence.Table;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Mar 18 11:33:46 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_attr_val" )
public class ShopAttrVal extends BaseModel {

    @Column(name = "attr_val" )
    private String attrVal;

    @Column(name = "id_attr_key" )
    private String idAttrKey;

    public String getAttrVal() {
        return attrVal;
    }

    public void setAttrVal(String attrVal) {
        this.attrVal = attrVal;
    }

    public String getIdAttrKey() {
        return idAttrKey;
    }

    public void setIdAttrKey(String idAttrKey) {
        this.idAttrKey = idAttrKey;
    }
}
