package com.ningyuan.mobile.model;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Tue Mar 24 19:29:46 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_order_item" )
public class ShopOrderItemModel extends BaseModel {

    /**
     * 数量
     */
    @FiledComment(text = "数量" )
    @Column(name = "count" )
    private BigDecimal count;

    /**
     * 商品id
     */
    @FiledComment(text = "商品id" )
    @Column(name = "id_goods" )
    private Long idGoods;

    /**
     * 所属订单id
     */
    @FiledComment(text = "所属订单id" )
    @Column(name = "id_order" )
    private Long idOrder;

    /**
     * skuId
     */
    @FiledComment(text = "skuId" )
    @Column(name = "id_sku" )
    private Long idSku;

    /**
     * 单价
     */
    @FiledComment(text = "单价" )
    @Column(name = "price" )
    private BigDecimal price;

    /**
     * 合计
     */
    @FiledComment(text = "合计" )
    @Column(name = "total_price" )
    private BigDecimal totalPrice;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public BigDecimal getCount() { return count; }

    public void setCount(BigDecimal count) { this.count = count; }

    public Long getIdGoods() {
        return this.idGoods;
    }

    public void setIdGoods(Long idGoods) {
        this.idGoods = idGoods;
    }

    public Long getIdOrder() {
        return this.idOrder;
    }

    public void setIdOrder(Long idOrder) {
        this.idOrder = idOrder;
    }

    public Long getIdSku() {
        return this.idSku;
    }

    public void setIdSku(Long idSku) {
        this.idSku = idSku;
    }

    public BigDecimal getPrice() { return price; }

    public void setPrice(BigDecimal price) { this.price = price; }

    public BigDecimal getTotalPrice() { return totalPrice; }

    public void setTotalPrice(BigDecimal totalPrice) { this.totalPrice = totalPrice; }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
