package com.ningyuan.mobile.model;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_order" )
public class ShopOrderModel extends BaseModel {

    /**
     * 收货信息
     */
    @FiledComment(text = "收货信息" )
    @Column(name = "id_address" )
    private Long idAddress;

    @Column(name = "open_id" )
    private String openId;

    /**
     * 订单备注
     */
    @FiledComment(text = "订单备注" )
    @Column(name = "message" )
    private String message;

    /**
     * 订单号
     */
    @FiledComment(text = "订单号" )
    @Column(name = "order_sn" )
    private String orderSn;

    /**
     * 实付金额
     */
    @FiledComment(text = "实付金额" )
    @Column(name = "real_price" )
    private String realPrice;

    /**
     * 状态
     */
    @FiledComment(text = "状态" )
    @Column(name = "status" )
    private Long status;

    /**
     * 总金额
     */
    @FiledComment(text = "总金额" )
    @Column(name = "total_price" )
    private String totalPrice;

    public Long getIdAddress() {
        return this.idAddress;
    }

    public void setIdAddress(Long idAddress) {
        this.idAddress = idAddress;
    }

    public String getOpenId() { return openId; }

    public void setOpenId(String openId) { this.openId = openId; }

    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getOrderSn() {
        return this.orderSn;
    }

    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    public String getRealPrice() {
        return this.realPrice;
    }

    public void setRealPrice(String realPrice) {
        this.realPrice = realPrice;
    }

    public Long getStatus() {
        return this.status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public String getTotalPrice() {
        return this.totalPrice;
    }

    public void setTotalPrice(String totalPrice) {
        this.totalPrice = totalPrice;
    }

}
