package com.ningyuan.mobile.model;

import javax.persistence.Column;
import com.ningyuan.base.annotation.FiledComment;
import javax.persistence.Table;
import com.ningyuan.base.BaseModel;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Wed Mar 18 11:33:46 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_category_banner_rel" )
public class ShopCategoryBannerRelModel extends BaseModel {

    /**
     * banner id
     */
    @FiledComment(text = "banner id" )
    @Column(name = "id_banner" )
    private Long idBanner;

    /**
     * 类别id
     */
    @FiledComment(text = "类别id" )
    @Column(name = "id_category" )
    private Long idCategory;

    @Column(name = "created_time" )
    private Date createdTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public Long getIdBanner() {
        return this.idBanner;
    }

    public void setIdBanner(Long idBanner) {
        this.idBanner = idBanner;
    }

    public Long getIdCategory() {
        return this.idCategory;
    }

    public void setIdCategory(Long idCategory) {
        this.idCategory = idCategory;
    }

    public Date getCreatedTime() {
        return this.createdTime;
    }

    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
