package com.ningyuan.mobile.model;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_goods_sku" )
public class ShopGoodsSkuModel extends BaseModel {

    /**
     * sku编码,格式:逗号分割的属性值id
     */
    @FiledComment(text = "sku编码,格式:逗号分割的属性值id" )
    @Column(name = "code" )
    private String code;

    /**
     * sku名称,格式:逗号分割的属性值
     */
    @FiledComment(text = "sku名称,格式:逗号分割的属性值" )
    @Column(name = "code_name" )
    private String codeName;

    /**
     * 商品id
     */
    @FiledComment(text = "商品id" )
    @Column(name = "id_goods" )
    private Long idGoods;

    /**
     * 市场价,原价
     */
    @FiledComment(text = "市场价,原价" )
    @Column(name = "marketing_price" )
    private BigDecimal marketingPrice;

    /**
     * 价格
     */
    @FiledComment(text = "价格" )
    @Column(name = "price" )
    private BigDecimal price;

    @FiledComment(text = "库存" )
    @Column(name = "stock" )
    private Integer stock;

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getCodeName() {
        return this.codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    public Long getIdGoods() {
        return this.idGoods;
    }

    public void setIdGoods(Long idGoods) {
        this.idGoods = idGoods;
    }

    public BigDecimal getMarketingPrice() { return marketingPrice; }

    public void setMarketingPrice(BigDecimal marketingPrice) { this.marketingPrice = marketingPrice; }

    public BigDecimal getPrice() { return price; }

    public void setPrice(BigDecimal price) { this.price = price; }

    public Integer getStock() { return stock; }

    public void setStock(Integer stock) { this.stock = stock; }
}
