package com.ningyuan.mobile.model;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Fri Apr 03 15:21:29 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_receive_record" )
public class ShopReceiveRecordModel extends BaseModel {

    @Column(name = "open_id" )
    private String openId;

    /**
     * 记录类型，1：领取红包，2：红包提现
     */
    @FiledComment(text = "记录类型，1：领取红包，2：红包提现" )
    @Column(name = "opt_type" )
    private String optType;

    /**
     * 金额或者红包个数
     */
    @FiledComment(text = "金额或者红包个数" )
    @Column(name = "amount" )
    private String amount;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getOptType() { return optType; }

    public void setOptType(String optType) { this.optType = optType; }

    public String getAmount() {
        return this.amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
