package com.ningyuan.mobile.model;

import javax.persistence.Column;
import javax.persistence.Table;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Sat Mar 21 14:55:34 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_address" )
public class ShopAddressModel extends BaseModel {

    /**
     * 收件人
     */
    @FiledComment(text = "收件人" )
    @Column(name = "name" )
    private String name;

    /**
     * 联系电话
     */
    @FiledComment(text = "联系电话" )
    @Column(name = "mobile" )
    private String mobile;

    @Column(name = "open_id" )
    private String openId;

    /**
     * 详细地址
     */
    @FiledComment(text = "详细地址" )
    @Column(name = "address_detail" )
    private String addressDetail;

    /**
     * 地区编码
     */
    @FiledComment(text = "地区编码" )
    @Column(name = "area_code" )
    private String areaCode;

    /**
     * 市
     */
    @FiledComment(text = "市" )
    @Column(name = "city" )
    private String city;

    /**
     * 区县
     */
    @FiledComment(text = "区县" )
    @Column(name = "district" )
    private String district;

    /**
     * 是否默认
     */
    @FiledComment(text = "是否默认" )
    @Column(name = "is_default" )
    private Boolean isDefault;

    /**
     * 是否删除
     */
    @FiledComment(text = "是否删除" )
    @Column(name = "is_delete" )
    private Boolean isDelete;

    /**
     * 邮政编码
     */
    @FiledComment(text = "邮政编码" )
    @Column(name = "post_code" )
    private String postCode;

    /**
     * 省
     */
    @FiledComment(text = "省" )
    @Column(name = "province" )
    private String province;

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getOpenId() {
        return this.openId;
    }

    public void setOpenId(String openId) {
        this.openId = openId;
    }

    public String getAddressDetail() {
        return this.addressDetail;
    }

    public void setAddressDetail(String addressDetail) {
        this.addressDetail = addressDetail;
    }

    public String getAreaCode() {
        return this.areaCode;
    }

    public void setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public Boolean getIsDefault() {
        return this.isDefault;
    }

    public void setIsDefault(Boolean isDefault) {
        this.isDefault = isDefault;
    }

    public Boolean getIsDelete() {
        return this.isDelete;
    }

    public void setIsDelete(Boolean isDelete) {
        this.isDelete = isDelete;
    }

    public String getPostCode() {
        return this.postCode;
    }

    public void setPostCode(String postCode) {
        this.postCode = postCode;
    }

    public String getProvince() {
        return this.province;
    }

    public void setProvince(String province) {
        this.province = province;
    }
}
