package com.ningyuan.mobile.model;

import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Column;
import javax.persistence.Table;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Fri Apr 03 11:07:12 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_award" )
public class ShopAwardModel extends BaseModel {

    /**
     * 奖品
     */
    @FiledComment(text = "奖品" )
    @Column(name = "prize" )
    private String prize;

    /**
     * 提示信息
     */
    @FiledComment(text = "提示信息" )
    @Column(name = "remark" )
    private String remark;

    /**
     * 中奖人数上限
     */
    @FiledComment(text = "中奖人数上限" )
    @Column(name = "up_limit" )
    private Long upLimit;

    /**
     * 中奖最低概率
     */
    @FiledComment(text = "中奖最低概率" )
    @Column(name = "min_rate" )
    private Double minRate;

    /**
     * 中将最高概率
     */
    @FiledComment(text = "中将最高概率" )
    @Column(name = "max_rate" )
    private Double maxRate;

    /**
     * 中奖人数
     */
    @FiledComment(text = "中奖人数" )
    @Column(name = "lottery_num" )
    private Long lotteryNum;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getPrize() {
        return this.prize;
    }

    public void setPrize(String prize) {
        this.prize = prize;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Long getUpLimit() {
        return this.upLimit;
    }

    public void setUpLimit(Long upLimit) {
        this.upLimit = upLimit;
    }

    public Double getMinRate() {
        return this.minRate;
    }

    public void setMinRate(Double minRate) {
        this.minRate = minRate;
    }

    public Double getMaxRate() {
        return this.maxRate;
    }

    public void setMaxRate(Double maxRate) {
        this.maxRate = maxRate;
    }

    public Long getLotteryNum() {
        return this.lotteryNum;
    }

    public void setLotteryNum(Long lotteryNum) {
        this.lotteryNum = lotteryNum;
    }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
