package com.ningyuan.mobile.model;

import javax.persistence.Column;
import com.ningyuan.base.BaseModel;
import com.ningyuan.base.annotation.FiledComment;

import javax.persistence.Table;
import java.math.BigDecimal;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Mar 26 12:00:49 CST 2020.</p>
 *
 * @author (zengrc)
 */

@Table ( name ="shop_goods" )
public class ShopGoodsModel extends BaseModel {

    /**
     * 产品简介
     */
    @FiledComment(text = "产品简介" )
    @Column(name = "descript" )
    private String descript;

    /**
     * 产品详情
     */
    @FiledComment(text = "产品详情" )
    @Column(name = "detail" )
    private String detail;

    /**
     * 大图相册列表,以逗号分隔
     */
    @FiledComment(text = "大图相册列表,以逗号分隔" )
    @Column(name = "gallery" )
    private String gallery;

    /**
     * 类别id
     */
    @FiledComment(text = "类别id" )
    @Column(name = "id_category" )
    private Long idCategory;

    /**
     * 是否上架
     */
    @FiledComment(text = "是否上架" )
    @Column(name = "is_on_sale" )
    private Integer isOnSale;

    /**
     * 名称
     */
    @FiledComment(text = "名称" )
    @Column(name = "name" )
    private String name;

    /**
     * 小图
     */
    @FiledComment(text = "小图" )
    @Column(name = "pic" )
    private String pic;

    /**
     * 价格
     */
    @FiledComment(text = "价格" )
    @Column(name = "price" )
    private BigDecimal price;

    @Column(name = "create_time" )
    private Date createTime;

    @Column(name = "update_time" )
    private Date updateTime;

    public String getDescript() {
        return this.descript;
    }

    public void setDescript(String descript) {
        this.descript = descript;
    }

    public String getDetail() {
        return this.detail;
    }

    public void setDetail(String detail) {
        this.detail = detail;
    }

    public String getGallery() {
        return this.gallery;
    }

    public void setGallery(String gallery) {
        this.gallery = gallery;
    }

    public Long getIdCategory() {
        return this.idCategory;
    }

    public void setIdCategory(Long idCategory) {
        this.idCategory = idCategory;
    }

    public Integer getIsOnSale() {
        return this.isOnSale;
    }

    public void setIsOnSale(Integer isOnSale) {
        this.isOnSale = isOnSale;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPic() {
        return this.pic;
    }

    public void setPic(String pic) {
        this.pic = pic;
    }

    public BigDecimal getPrice() { return price; }

    public void setPrice(BigDecimal price) { this.price = price; }

    public Date getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    public Date getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

}
