package com.ningyuan.wx.service.impl;

import com.ningyuan.wx.daomapper.mapper.WxLocationMapper;
import com.ningyuan.wx.model.WxLocationModel;
import com.ningyuan.wx.service.IWxLocationService;
import com.ningyuan.base.BaseServiceImpl;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy
 * <p>Date: Mon Jan 21 10:34:58 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class WxLocationServiceImpl extends BaseServiceImpl<WxLocationMapper, WxLocationModel> implements IWxLocationService {

}
