package com.ningyuan.wx.service.impl;

import com.ningyuan.wx.daomapper.mapper.WxMsgResultMapper;
import com.ningyuan.wx.model.WxMsgResultModel;
import com.ningyuan.wx.service.IWxMsgResultService;
import com.ningyuan.base.BaseServiceImpl;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed May 15 10:20:36 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class WxMsgResultServiceImpl extends BaseServiceImpl<WxMsgResultMapper, WxMsgResultModel> implements IWxMsgResultService {

}
