package com.ningyuan.wx.service.impl;

import com.ningyuan.wx.daomapper.mapper.WxNotifyInfoMapper;
import com.ningyuan.wx.model.WxNotifyInfoModel;
import com.ningyuan.wx.service.IWxNotifyInfoService;
import com.ningyuan.base.BaseServiceImpl;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue Nov 20 14:30:10 CST 2018.</p>
 *
 * @author (zengrc)
 */

@Service
public class WxNotifyInfoServiceImpl extends BaseServiceImpl<WxNotifyInfoMapper, WxNotifyInfoModel> implements IWxNotifyInfoService {



}
