package com.ningyuan.wx.service.impl;

import com.ningyuan.wx.daomapper.mapper.WxPay2userResultMapper;
import com.ningyuan.wx.model.WxPay2userResultModel;
import com.ningyuan.wx.service.IWxPay2userResultService;
import com.ningyuan.base.BaseServiceImpl;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue May 14 17:52:01 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class WxPay2userResultServiceImpl extends BaseServiceImpl<WxPay2userResultMapper, WxPay2userResultModel> implements IWxPay2userResultService {

}
