package com.ningyuan.wx.service.impl;

import com.ningyuan.wx.daomapper.mapper.WxRedPackResultMapper;
import com.ningyuan.wx.model.WxRedPackResultModel;
import com.ningyuan.wx.service.IWxRedPackResultService;
import com.ningyuan.base.BaseServiceImpl;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Thu Feb 14 11:29:54 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class WxRedPackResultServiceImpl extends BaseServiceImpl<WxRedPackResultMapper, WxRedPackResultModel> implements IWxRedPackResultService {

}
