package com.ningyuan.wx.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.wx.daomapper.mapper.WxsaSubscribeMapper;
import com.ningyuan.wx.model.wxsa.WxsaSubscribeModel;
import com.ningyuan.wx.service.IWxsaSubscribeService;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy
 * <p>Date: Mon Oct 07 17:14:41 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class WxsaSubscribeServiceImpl extends BaseServiceImpl<WxsaSubscribeMapper, WxsaSubscribeModel> implements IWxsaSubscribeService {

}
