package com.ningyuan.wx.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.wx.daomapper.mapper.WxsaOutMsgMapper;
import com.ningyuan.wx.model.wxsa.WxsaOutMsgModel;
import com.ningyuan.wx.service.IWxsaOutMsgService;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Mon Aug 12 14:50:43 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class WxsaOutMsgServiceImpl extends BaseServiceImpl<WxsaOutMsgMapper, WxsaOutMsgModel> implements IWxsaOutMsgService {

}
