package com.ningyuan.route.daomapper.mapper;

import com.ningyuan.route.model.BgRouteModel;
import tk.mybatis.mapper.common.Mapper;

import java.util.List;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface BgRouteMapper extends Mapper<BgRouteModel> {

    List<BgRouteModel> getRouteByRole(Long roleId);

//    List<BgRouteRoleDto> getRouteByRoleId(Long roleId);
}
