package com.ningyuan.route.daomapper.mapper;

import com.ningyuan.route.model.BgUserModel;
import tk.mybatis.mapper.common.Mapper;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface BgUserMapper extends Mapper<BgUserModel> {

}
