package com.ningyuan.route.daomapper.mapper;

import com.ningyuan.route.dto.SettingDto;
import com.ningyuan.route.dto.ShopUserDto;
import com.ningyuan.route.dto.ShopUserQueryDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface ShopUserMapper {
    List<ShopUserDto> listUser(ShopUserQueryDto queryDto);

    void updateUserByid(ShopUserDto shopUserDto);

    String getPerformanceRatio();

    String getDividendRatio();

    void updateSetting(SettingDto settingDto);

    void updateRedpacketAmount(@Param("id") Long id, @Param("redpacketAmount") String redpacketAmount);

    void insertRecord(@Param("openId") String openId, @Param("redpacketAmount") String redpacketAmount, @Param("optType") String optType);
}
