package com.ningyuan.route.daomapper.mapper;

import com.ningyuan.route.dto.InviteQueryDto;
import com.ningyuan.route.dto.ShopAddressDto;
import com.ningyuan.route.dto.ShopInviterDto;
import com.ningyuan.route.dto.ShopOrderDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface ShopCustomerMapper {
    List<ShopInviterDto> getInviteList(InviteQueryDto inviteQueryDto);

    List<ShopAddressDto> getAddressList(@Param("mobile") String mobile, @Param("defaultAddress") String defaultAddress);

    List<ShopOrderDto> getOrderList(@Param("orderSn") String orderSn);

    void updateOrder(ShopOrderDto orderDto);
}
