package com.ningyuan.route.daomapper.mapper;

import com.ningyuan.route.dto.SettingDto;
import com.ningyuan.route.dto.ShopMarketRatioDto;
import com.ningyuan.route.dto.ShopUserDto;
import com.ningyuan.route.dto.ShopUserQueryDto;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * generated by Generate Mapper.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface ShopUserMapper {
    List<ShopUserDto> listConfirmUser(ShopUserQueryDto queryDto);

    List<ShopUserDto> listUnConfirmUser(ShopUserQueryDto queryDto);

    void updateUserByid(ShopUserDto shopUserDto);

    List<ShopMarketRatioDto> getMarketRatio();

    void updateMarketRatio(List<ShopMarketRatioDto> list);

    void updateRedpacketAmount(@Param("id") Long id, @Param("amount") Integer amount);

    void insertRecord(@Param("openId") String openId, @Param("addAmount") Integer addAmount, @Param("optType") String optType);

    void updateConfirm(Long id);

    Integer getCustomer(Long id);
}
