package com.ningyuan.wx.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.wx.model.WxRelateModel;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Mon Mar 25 15:39:26 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxCommonRelateService extends IBaseService<WxRelateModel>, IWxRelateService<WxRelateModel> {
    WxRelateModel getByTypeOpenId(String openId);
}
