package com.ningyuan.wx.service;

import com.ningyuan.wx.model.WxLocationModel;
import com.ningyuan.base.IBaseService;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Mon Jan 21 10:34:58 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxLocationService extends IBaseService<WxLocationModel> {
}
