package com.ningyuan.wx.service;

import com.ningyuan.wx.model.WxMsgResultModel;
import com.ningyuan.base.IBaseService;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed May 15 10:20:36 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxMsgResultService extends IBaseService<WxMsgResultModel> {

}
