package com.ningyuan.wx.service;

import com.ningyuan.wx.model.WxNotifyInfoModel;
import com.ningyuan.base.IBaseService;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue Nov 20 14:30:10 CST 2018.</p>
 *
 * @author (zengrc)
 */

public interface IWxNotifyInfoService extends IBaseService<WxNotifyInfoModel> {

}
