package com.ningyuan.wx.service;

import com.ningyuan.wx.model.WxPay2userResultModel;
import com.ningyuan.base.IBaseService;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Tue May 14 17:52:01 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxPay2userResultService extends IBaseService<WxPay2userResultModel> {

}
