package com.ningyuan.wx.service;

import com.ningyuan.wx.model.WxRedPackResultModel;
import com.ningyuan.base.IBaseService;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Thu Feb 14 11:29:54 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxRedPackResultService extends IBaseService<WxRedPackResultModel> {

}
