package com.ningyuan.wx.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.wx.model.wxsa.WxsaSubscribeModel;

/**
 * generated by Generate Service.groovy
 * <p>Date: Mon Oct 07 17:14:41 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxsaSubscribeService extends IBaseService<WxsaSubscribeModel>, IWxGetByOpenId<WxsaSubscribeModel> {

}
