package com.ningyuan.wx.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.wx.model.wxsa.WxsaOutMsgModel;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Mon Aug 12 14:50:43 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxsaOutMsgService extends IBaseService<WxsaOutMsgModel> {

}
