package com.ningyuan.wx.service;

import com.ningyuan.base.IBaseService;
import com.ningyuan.wx.model.wxsa.WxsaCustomerModel;

/**
 * generated by Generate Service.groovy
 * <p>Date: Tue Aug 20 09:48:12 CST 2019.</p>
 *
 * @author (zengrc)
 */

public interface IWxsaCustomerService extends IBaseService<WxsaCustomerModel>, IWxGetByOpenId<WxsaCustomerModel> {
    void saveCustomer(String openId, WxsaCustomerModel customerModel);
}
