package com.ningyuan.wx.service;

import com.ningyuan.wx.dto.GetTokenByCodeResultDto;
import com.ningyuan.wx.dto.WxUserDto;
import com.ningyuan.wx.model.WxUserModel;
import com.ningyuan.base.IBaseService;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Oct 24 09:50:21 CST 2018.</p>
 *
 * @author (zengrc)
 */

public interface IWxUserService extends IBaseService<WxUserModel>, IWxGetByOpenId<WxUserModel>{

    WxUserDto getDtoByOpenId(String openId);

    void saveWxUser(GetTokenByCodeResultDto getTokenByCodeResultDto, String promoteType);

}
