package com.ningyuan.route.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.route.daomapper.mapper.BgResourceMapper;
import com.ningyuan.route.model.BgResourceModel;
import com.ningyuan.route.service.IBgResourceService;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class BgResourceServiceImpl extends BaseServiceImpl<BgResourceMapper, BgResourceModel> implements IBgResourceService {

    @Override
    public List<BgResourceModel> getResourcesByRole(long id) {
        return this.mapper.getResourcesByRole(id);
    }

    /*@Override
    public List<BgResourceRouteDto> getResourcesByRoute(long id) {
        return this.mapper.getResourcesByRoute(id);
    }*/
}
