package com.ningyuan.route.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.route.daomapper.mapper.BgRoleMapper;
import com.ningyuan.route.model.BgRoleModel;
import com.ningyuan.route.service.IBgRoleService;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class BgRoleServiceImpl extends BaseServiceImpl<BgRoleMapper, BgRoleModel> implements IBgRoleService {

    @Override
    public List<BgRoleModel> getRolesByUser(Long id) {
        return this.mapper.getRolesByUser(id);
    }
}
