package com.ningyuan.route.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.route.daomapper.mapper.BgRouteMapper;
import com.ningyuan.route.model.BgRouteModel;
import com.ningyuan.route.service.IBgRouteService;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class BgRouteServiceImpl extends BaseServiceImpl<BgRouteMapper, BgRouteModel> implements IBgRouteService {

    @Override
    public List<BgRouteModel> getRouteByRole(Long roleId) {
        return this.mapper.getRouteByRole(roleId);
    }

//    @Override
//    public List<BgRouteRoleDto> getRouteByRoleId(Long roleId) {
//        return this.mapper.getRouteByRoleId(roleId);
//    }
}
