package com.ningyuan.route.service.impl;

import com.ningyuan.base.BaseServiceImpl;
import com.ningyuan.route.daomapper.mapper.BgUserMapper;
import com.ningyuan.route.model.BgUserModel;
import com.ningyuan.route.service.IBgUserService;
import org.springframework.stereotype.Service;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class BgUserServiceImpl extends BaseServiceImpl<BgUserMapper, BgUserModel> implements IBgUserService {

    @Override
    public BgUserModel getUserByUsername(String userName) {
        BgUserModel bgUserModel = new BgUserModel();
        bgUserModel.setUsername(userName);
        bgUserModel = this.selectOne(bgUserModel);
        return bgUserModel;
    }
}
