package com.ningyuan.route.service.impl;

import com.ningyuan.route.daomapper.mapper.ShopCustomerMapper;
import com.ningyuan.route.dto.InviteQueryDto;
import com.ningyuan.route.dto.ShopAddressDto;
import com.ningyuan.route.dto.ShopInviterDto;
import com.ningyuan.route.dto.ShopOrderDto;
import com.ningyuan.route.service.IShopCustomerService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

/**
 * generated by Generate Service.groovy 
 * <p>Date: Wed Mar 20 14:42:20 CST 2019.</p>
 *
 * @author (zengrc)
 */

@Service
public class ShopCustomerServiceImpl implements IShopCustomerService {

    @Autowired
    private ShopCustomerMapper shopCustomerMapper;


    @Override
    public List<ShopInviterDto> getInviteList(InviteQueryDto inviteQueryDto) {
        return shopCustomerMapper.getInviteList(inviteQueryDto);
    }

    @Override
    public List<ShopAddressDto> getAddressList(String mobile, String defaultAddress) {
        return shopCustomerMapper.getAddressList(mobile, defaultAddress);
    }

    @Override
    public List<ShopOrderDto> getOrderList(String orderSn) {
        return shopCustomerMapper.getOrderList(orderSn);
    }

    @Override
    public void updateOrder(ShopOrderDto orderDto) {
        shopCustomerMapper.updateOrder(orderDto);
    }
}
